services:
  bitcoin:
    image: bitcoin:22.0
    build: ./bitcoin
    volumes:
      - ${btc_dir:?err}:/bitcoin/.bitcoin
    network_mode: "host"
  electrs:
    image: electrs:0.9.6
    build: ./electrs
    network_mode: "host"
    volumes:
      - ${electrs_dir:?err}:/data
      - ${btc_dir:?err}:/bitcoin
    command: [
      "--daemon-dir=/bitcoin",
      "--db-dir=/data/db",
    ]
    depends_on:
      - bitcoin
